name: "Comprueba hitos y milestones"
on:
  pull_request:
    paths:
      - 'proyectos/[01234567].md'
      - '!objetivos/*.md'

jobs:
  obtain-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio del diff
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Extrae usuario y nombre del repo
        uses: actions/github-script@v3
        id: user_repo
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ There's no repo URL in this diff with required format")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Encontrado repo " + repo + " para usuario " + user )
                console.log( "::set-output name=user::" + user )
                console.log( "::set-output name=repo::" + repo )
            }
  tests-sobre-fuentes:
    needs: obtain-repo
    env:
      user: ${{ needs.obtain-repo.outputs.user }}
      repo: ${{ needs.obtain-repo.outputs.repo }}
    steps:
      - name: Descarga repo usuario y decodifica configuración
        uses: actions/checkout@v2
        with:
          repository: '${{env.repo}}/${{env.user}}'
      - name: Descarga tests
        run: |
          wget https://raw.githubusercontent.com/JJ/CC-21-22/master/src/check-hitos.t
          mkdir t
          mv check-hitos.t t/check-hitos.t
